version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "RicardoCopriz2025"
    ports:
      - "1433:1433"
   # volumes:
    #  - /home/redlab/docker_volumes/sqlserver: /var/opt/mssql/data # Mapeo de carpeta
